import {NavLink} from 'react-router-dom';
import {ArrowUpRight,MessageCircle,Activity,Users,Info} from 'lucide-react';
import {useAnalysis} from './AnalysisProvider';
import {useChat} from '../chat/ChatProvider';
import {ConflictTimeline} from './ConflictTimeline';
import {EmotionDistribution,SignalTimeline} from './DashboardCharts';
import {speakerSummaries} from './dashboardData';
import {emotionLabels,percent} from '../../models/analysis';
import {participants} from '../../models/chat';
export function AnalysisDashboard() {
  const {snapshot,status,error,retry}=useAnalysis();const {messages,inspectMessage}=useChat();
  const hero=<><p className="eyebrow">CONVERSATION INTELLIGENCE · DEMO</p><h1>See the bigger picture</h1><p>A conversation, seen in context. Explore illustrative signals, pivotal moments and each participant’s conversational arc.</p></>;
  if(!snapshot||status==='error')return <section className="timeline-page analysis-dashboard">{hero}<div className="dashboard-empty" role={status==='error'?'alert':'status'}><MessageCircle size={30}/><h2>{status==='error'?'Analysis unavailable':status==='loading'?'Preparing the dashboard…':'No conversation turns yet.'}</h2><p>{status==='error'?error:'Mock analysis appears once your local conversation has a message.'}</p>{status==='error'?<button className="analytics-toggle" onClick={retry}>Retry analysis</button>:<NavLink to="/chat" className="analytics-toggle">Back to conversation <ArrowUpRight size={14}/></NavLink>}</div></section>;
  const summaries=speakerSummaries(snapshot);
  const averageConflict=snapshot.messages.reduce((sum,row)=>sum+row.conflict,0)/snapshot.messages.length;
  const strongestConcern=snapshot.messages.reduce((max,row)=>row.emotions.concern>max.emotions.concern?row:max,snapshot.messages[0]);
  return <section className="timeline-page analysis-dashboard" aria-busy={status==='loading'}>{hero}
    <div className="dashboard-mode-note"><Info size={14}/><span><strong>{snapshot.mode==='MOCK'?'Mock fixtures · no AI inference':'Model estimates'}</strong> {status==='loading'?'Refreshing results…':'Signals describe language patterns, not psychological facts.'}</span></div>
    <div className="dashboard-kpis"><div><MessageCircle size={17}/><span>Conversation turns</span><strong>{messages.length}</strong><small>{snapshot.messages.length} illustrated analyses</small></div><div><Activity size={17}/><span>Average conflict signal</span><strong>{percent(averageConflict)}<small>/100</small></strong><small>Mean of fixture scores</small></div><div><Users size={17}/><span>Participants</span><strong>{summaries.filter(s=>s.messageCount>0).length}</strong><small>Speaker-aware context</small></div><div><ArrowUpRight size={17}/><span>Peak tension</span><strong>{snapshot.peakTension?`#${snapshot.peakTension}`:'—'}</strong><small>Illustrative turning point</small></div></div>
    <section className="dashboard-summary dashboard-card" aria-label="Conversation summary"><div className="dashboard-card-heading"><div><span className="eyebrow">THE CONVERSATION AT A GLANCE</span><h2>Conversation summary</h2></div><span className="pill">Mock</span></div><p>{snapshot.messages.length} turns between {participants.map(p=>p.name).join(' and ')}. {snapshot.escalationStart?`The fixtures mark an increase in tension at message ${snapshot.escalationStart}, with the highest conflict signal at message ${snapshot.peakTension}.`:'These fixtures have no escalation-start marker.'} The current illustrated direction is <strong>{snapshot.direction}</strong>.</p><small>This summary describes hand-authored UI data. No model has interpreted the conversation.</small></section>
    <ConflictTimeline/>
    <section className="dashboard-speakers" aria-label="Speaker comparison"><div className="dashboard-section-heading"><h2>Speaker comparison</h2><span>Estimated signals · fixture averages</span></div><div className="speaker-grid">{summaries.map(speaker=><article className="speaker-card" key={speaker.id} aria-label={`${speaker.name} analysis`}><header><span className={`contact-avatar ${speaker.variant}`}>{speaker.name[0]}</span><div><h3>{speaker.name}</h3><p>Dominant signal <strong>{speaker.dominantEmotion?emotionLabels[speaker.dominantEmotion]:'No data'}</strong></p></div><span className="pill">{speaker.messageCount} {speaker.messageCount===1?'turn':'turns'}</span></header><div className="speaker-metrics"><div><span>Average sentiment</span><strong>{speaker.averageSentiment?.toFixed(2)??'—'}</strong></div><div><span>Conflict contribution</span><strong>{speaker.conflictContribution===null?'—':`${percent(speaker.conflictContribution)}%`}</strong></div><div><span>Sarcasm signal</span><strong>{speaker.sarcasm===null?'—':`${percent(speaker.sarcasm)}%`}</strong></div><div><span>Toxicity signal</span><strong>{speaker.toxicity===null?'—':`${percent(speaker.toxicity)}%`}</strong></div></div><div className="speaker-escalations"><span>Major escalation points</span>{speaker.escalationPoints.length?speaker.escalationPoints.map(event=><button key={event.kind+event.sequence} onClick={()=>inspectMessage(event.messageId)}>#{event.sequence} · {event.kind==='peak'?'Peak':'Shift'}</button>):<small>None in this fixture</small>}</div></article>)}</div><p className="dashboard-card-note">Contribution shows each participant’s share of the illustrated conflict signals.</p></section>
    <div className="dashboard-chart-grid"><EmotionDistribution snapshot={snapshot}/><SignalTimeline snapshot={snapshot} signal="sarcasm"/><SignalTimeline snapshot={snapshot} signal="toxicity"/></div>
    <section className="dashboard-card dashboard-key-insights" aria-label="Key insights"><div className="dashboard-card-heading"><div><span className="eyebrow">MOMENTS WORTH A CLOSER LOOK</span><h2>Key insights & escalation points</h2></div></div><div className="insight-event-list">{snapshot.events.map(event=><button key={event.kind+event.sequence} onClick={()=>inspectMessage(event.messageId)}><span className={`event-dot ${event.kind}`}/><div><strong>{event.label}</strong><small>Message #{event.sequence} · illustrative marker</small></div><ArrowUpRight size={16}/></button>)}{strongestConcern&&<button onClick={()=>inspectMessage(strongestConcern.messageId)}><span className="event-dot concern"/><div><strong>Strongest concern signal</strong><small>Message #{strongestConcern.sequence} · {percent(strongestConcern.emotions.concern)}% fixture score</small></div><ArrowUpRight size={16}/></button>}</div></section>
    <section className="dashboard-card dashboard-inspection" aria-label="Message inspector list"><div className="dashboard-card-heading"><div><span className="eyebrow">FROM OVERVIEW TO EVIDENCE</span><h2>Message inspector</h2></div><span className="pill">{snapshot.messages.length} turns</span></div><p className="dashboard-card-note">Select any turn for signal scores, context and provenance.</p><div className="inspection-list">{snapshot.messages.map(row=>{const message=messages.find(m=>m.id===row.messageId);const speaker=participants.find(p=>p.id===row.speakerId);return <button key={row.messageId} aria-label={`Inspect message ${row.sequence} from ${speaker?.name}`} onClick={()=>inspectMessage(row.messageId)}><span className="inspection-sequence">{row.sequence.toString().padStart(2,'0')}</span><div className="inspection-text"><span>{speaker?.name}</span><strong>{message?.text??'Message unavailable'}</strong></div><div className="inspection-scores"><span><small>Conflict</small>{percent(row.conflict)}%</span><span><small>Sarcasm</small>{percent(row.signals.sarcasm)}%</span><span><small>Toxicity</small>{percent(row.signals.toxicity)}%</span></div></button>;})}</div></section>
  </section>;
}

