import {useId} from 'react';
import {Area,AreaChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {percent,type ConversationAnalysis} from '../../models/analysis';
import {emotionDistribution} from './dashboardData';
const colors=['#ff6bbb','#a584e8','#7597d4','#7bbfa9','#d4a46c','#bba0e2'];
export function EmotionDistribution({snapshot}:{snapshot:ConversationAnalysis}) {
  const distribution=emotionDistribution(snapshot);
  const modelEmotions=snapshot.messages.every(row=>row.evidence.some(e=>e.source==='MODEL'&&e.label==='GoEmotions emotion'));
  return <section className="dashboard-card emotion-distribution" aria-label="Emotion signal distribution"><div className="dashboard-card-heading"><div><span className="eyebrow">RELATIVE SIGNAL MIX</span><h2>Emotion distribution</h2></div><span className="pill">{modelEmotions?"Mapped model signals":"Mock"}</span></div><div className="distribution-content"><div className="distribution-donut" role="img" aria-label="Relative mix of illustrated emotion signals"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={distribution} dataKey="value" nameKey="label" innerRadius="63%" outerRadius="88%" stroke="none" isAnimationActive={false}>{distribution.map((row,i)=><Cell key={row.key} fill={colors[i]}/>)}</Pie><Tooltip formatter={value=>`${percent(Number(value))}%`} contentStyle={{background:'#211529',border:'1px solid #57345e',borderRadius:8,fontSize:10}}/></PieChart></ResponsiveContainer></div><div className="distribution-legend">{distribution.map((row,i)=><div key={row.key}><i style={{background:colors[i]}}/><span>{row.label}</span><strong>{percent(row.value)}%</strong></div>)}</div></div><p className="dashboard-card-note">{modelEmotions?"Relative mix of mapped model signals, including documented proxies. This does not measure anyone’s feelings.":"Relative mix across fixture scores. This does not measure anyone’s feelings."}</p></section>;
}
export function SignalTimeline({snapshot,signal}:{snapshot:ConversationAnalysis;signal:'sarcasm'|'toxicity'}) {
  const gradient=useId().replace(/[^a-zA-Z0-9-]/g,'');const color=signal==='sarcasm'?'#a59ae9':'#db84b1';
  const modelSignal=snapshot.messages.every(row=>row.evidence.some(e=>e.source==='MODEL'&&e.label===(signal==='sarcasm'?'Sarcasm classifier':'Toxicity classifier')));
  const rows=snapshot.messages.map(row=>({sequence:row.sequence,value:percent(row.signals[signal])}));
  return <section className="dashboard-card" aria-label={`${signal} timeline`}><div className="dashboard-card-heading"><div><span className="eyebrow">LANGUAGE SIGNAL OVER TIME</span><h2>{signal==='sarcasm'?'Sarcasm':'Toxicity'} timeline</h2></div><span className="pill">{modelSignal?"Model estimates":"Mock"}</span></div><div className="signal-timeline-plot"><ResponsiveContainer width="100%" height="100%" minWidth={0}><AreaChart data={rows} margin={{top:12,right:5,left:-8,bottom:0}} accessibilityLayer><defs><linearGradient id={gradient} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity={.25}/><stop offset="100%" stopColor={color} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#31243b" vertical={false} strokeDasharray="3 5"/><XAxis dataKey="sequence" axisLine={false} tickLine={false} tick={{fontSize:9,fill:'#9b80ae'}} minTickGap={12}/><YAxis domain={[0,100]} ticks={[0,50,100]} width={32} axisLine={false} tickLine={false} tick={{fontSize:8,fill:'#8c709f'}}/><Tooltip labelFormatter={label=>`Message ${label}`} formatter={value=>[`${value}%`,signal]} contentStyle={{background:'#211529',border:'1px solid #57345e',borderRadius:8,fontSize:10}}/><Area type="linear" dataKey="value" stroke={color} fill={`url(#${gradient})`} strokeWidth={2} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div><p className="dashboard-card-note">{modelSignal?"Estimated 0–100 linguistic signal by message sequence; inspect each message for model evidence.":"Illustrative 0–100 signal scores by message sequence."}</p></section>;
}
